# docker-compose.yml
version: '3.7'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - TZ=Asia/Kolkata
    networks:
      - app-network

  db:
    image: nouchka/sqlite3
    volumes:
      - ./data:/data
    networks:
      - app-network

  streamlit:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - TZ=Asia/Kolkata
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
