version: '3.8'

services:
  web:
    build: .
    ports:
      - "8002:8002"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: skills_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
